// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnicalAssessment.Core.Context;

#nullable disable

namespace TechnicalAssessment.Core.Migrations
{
    [DbContext(typeof(TechAssessmentDbContext))]
    partial class TechAssessmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("TechnicalAssessment.Core.Model.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("171c8825-c739-46a4-b66d-2bd7c2b5f056"),
                            CategoryId = new Guid("809e7a3c-2895-41ea-9961-f375b12a1d41"),
                            CreatedOn = new DateTime(2025, 6, 24, 16, 17, 25, 446, DateTimeKind.Utc).AddTicks(3238),
                            Description = "Gaming Laptop",
                            IsDeleted = false,
                            Name = "Laptop",
                            Price = 1500m
                        },
                        new
                        {
                            Id = new Guid("847274a4-8b0e-44a0-9c0e-516e73be4468"),
                            CategoryId = new Guid("9e45b88a-6811-4d94-b00f-57e74d5a15ba"),
                            CreatedOn = new DateTime(2025, 6, 24, 16, 17, 25, 446, DateTimeKind.Utc).AddTicks(3261),
                            Description = "Latest Android",
                            IsDeleted = false,
                            Name = "Smartphone",
                            Price = 800m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
